### ISSUE TITLE
How to update an entity?

### ISSUE THREAD

**Issue by rutgersmit** [dutchgrit/afasclient#2]
Hi,

Thanks for this interesting project.

I was wondering how to update an entity. The documentation stops after the subtitle 'Updating' :(

Thanks,
Rutger

**Comment by LucasVos** [comment]
Hi Rutger,

You're welcome! I have just updated the readme and included the 'Updating' part as well as some other features in the latest nuget version of the library. Let me know if anything is unclear! Happy coding.
