### ISSUE TITLE
OrderBy expression throws exceptions

### ISSUE THREAD

**Issue by imMarkdeVries** [dutchgrit/afasclient#3]
var invoices = await client.Query<ProfitDebtorInvoices>()
        .Skip(50)
        .Take(10)
        .OrderBy(x => x.DebtorID)
        .GetAsync();

The orderBy sections throws an exception  
Invalid expression. (Parameter 'GetJsonPropertyName')

Am i missing something?

I'm working on target framework .net 5

**Comment by LucasVos** [comment]
Maybe you forgot to specifiy the GetConnector Generictype in the Query<T>() in the above example? Hmm.. Probably not, otherwise you would have a compile time error with the OrderBy.
```
var invoices = await client.Query<SomeGetConnectorType>().Skip(10).GetAsync();
```
The classes for your specific GetConnectors can be generated by the use of the afascli commandline tool.

Just to verify -> 
Which version of the AfasClient nuget library do you use? I can remember some (old) issue with a previous version. Could you verify that you use the latest version?

**Comment by imMarkdeVries** [comment]
Dear Lucas,

nuget version 1.0.0.53 
.NET 5


generated with afas-cli (best tool ever)

i'm not a big C# pro but this worked for me on another project

  private string GetJsonPropertyName(Expression<Func<T, object>> fieldExpression)
        {
            MemberExpression memberExpression = null;

            if (fieldExpression.Body.NodeType == ExpressionType.Convert)
            {
                memberExpression = ((UnaryExpression) fieldExpression.Body).Operand as MemberExpression;
            }
            else if (fieldExpression.Body.NodeType == ExpressionType.MemberAccess)
            {
                memberExpression = fieldExpression.Body as MemberExpression;
            }

            if (memberExpression == null)
            {
                throw new ArgumentException("Not a member access", $"expression");
            }

            return ((JsonPropertyNameAttribute) memberExpression.Member.GetCustomAttribute(
                typeof(JsonPropertyNameAttribute))!)?.Name ?? string.Empty;
        }

**Comment by LucasVos** [comment]
(best tool ever) => ❤️ 
yes, i can confirm that it's indeed not working correctly! 
your "another" project looks like a very perfect solution 😄 haha. thanx! 
A new nuget package is building in 5 minutes. Please let me know if it solves your problem.

**Comment by imMarkdeVries** [comment]
it is solved :)
thank you for your quick response.

I really like afas-cli. It works like it should.
