### ISSUE TITLE
Feature request: trace or verbose information

### ISSUE THREAD

**Issue by nielsverkaart** [dutchgrit/afasclient#4]
Hi Lucas,

First off. Great product!! It could save me lots of hours of plumbing.

I would find it useful to see the bare post or get, and response. When I have errors I can then paste that in Postman or Swagger. I then also hope to get more detailed feedback. Or at least I'm able to show AFAS employees my problem, which they could reproduce or show me the mistake I make.
Or maybe this option is already there ;)

cheers,
Niels

**Comment by LucasVos** [comment]
Dear Niels,

I have updated the library to include http tracing capabilities. Please upgrade to 1.0.0.62
More info [here](https://github.com/dutchgrit/afasclient/blob/master/Tracing.MD)

Let me know if it works as expected.

Cheers, Lucas

**Comment by nielsverkaart** [comment]
Really nice Lucas,

Works like a charm. This will certainly help me.

Thanks and all the best, Niels
