### ISSUE TITLE
Feature request: Possibility to set HttpClient per AfasClient

### ISSUE THREAD

**Issue by coenm** [dutchgrit/afasclient#5]
Hi,

I was wondering if it is possible to update the ctor making it possible to inject an HttpClient per AfasClient. 

ie:
```cs

// alreade existing params:
var memberNumber= "";
var token = "";
var env = Environments.Test;
// new  param
var httpClient = new HttpClient();
// ctor
var client = new AfasClient(memberNumber, token , env, httpClient);

// The new ctor could then then be like:
public AfasClient(int MemberNumber, string Token, Environments env = Environments.Production, HttpClient? client = null)
{
  if (httpClient == null)
    // use global httpclient
  else
    // use custom http client

 // ......
}
```

I noticed that it is possible overwrite the global HttpClient by using  ` GeneralBase.httpClient = new HttpClient(); ` but this doens't work well with our (in parallell executing) unittest where we want to validate requests and mock responses using a fake httpClient.

**Comment by LucasVos** [comment]
Yes, the library uses a shared/static httpclient as recommended (https://learn.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/). But I understand your use case and it seems doable 👍 
Please try the [1.0.0.65-beta](https://www.nuget.org/packages/DutchGrit.AfasClient/1.0.0.65-beta) version. And just let me know if it works as expected :-)

**Comment by coenm** [comment]
Thank you for your quick implementation. I will give it a try probably today or tomorrow. I will let you know if it works

**Comment by coenm** [comment]
It works
